// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"plat_order/internal/dao/internal"
)

// internalLhCoinSymbolDao is internal type for wrapping internal DAO implements.
type internalLhCoinSymbolDao = *internal.LhCoinSymbolDao

// lhCoinSymbolDao is the data access object for table lh_coin_symbol.
// You can define custom methods on it to extend its functionality as you wish.
type lhCoinSymbolDao struct {
	internalLhCoinSymbolDao
}

var (
	// LhCoinSymbol is globally public accessible object for table lh_coin_symbol operations.
	LhCoinSymbol = lhCoinSymbolDao{
		internal.NewLhCoinSymbolDao(),
	}
)

// Fill with you ideas below.
